steps:
#step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/mykubernetes-234210/wordsmith:latest || exit 0'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t',
   'gcr.io/mykubernetes-234210/wordsmith:$BRANCH_NAME-$COMMIT_SHA',
   '.'
  ]
